spring:
  application:
    name: keyword_watcher

  profiles:
    default: local

crawling:
  connection:
    user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    timeout: 30s
    max-body-size: 10485760  # 10MB

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:~/keywordWatcherApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true # (boot 2.5 이후) Hibernate 초기화 이후 data.sql 실행

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:~/keywordWatcherApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never